# coding: utf-8

"""
    WhatsApp Food Ordering System

    A food ordering system with WhatsApp integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.menu_item_out import MenuItemOut

class TestMenuItemOut(unittest.TestCase):
    """MenuItemOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MenuItemOut:
        """Test MenuItemOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MenuItemOut`
        """
        model = MenuItemOut()
        if include_optional:
            return MenuItemOut(
                name = '',
                description = '',
                price = 1.337,
                is_available = True,
                id = 56
            )
        else:
            return MenuItemOut(
                name = '',
                description = '',
                price = 1.337,
                id = 56,
        )
        """

    def testMenuItemOut(self):
        """Test MenuItemOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
