# coding: utf-8

"""
    WhatsApp Food Ordering System

    A food ordering system with WhatsApp integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_status_update import OrderStatusUpdate

class TestOrderStatusUpdate(unittest.TestCase):
    """OrderStatusUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderStatusUpdate:
        """Test OrderStatusUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderStatusUpdate`
        """
        model = OrderStatusUpdate()
        if include_optional:
            return OrderStatusUpdate(
                status = ''
            )
        else:
            return OrderStatusUpdate(
                status = '',
        )
        """

    def testOrderStatusUpdate(self):
        """Test OrderStatusUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
