# coding: utf-8

"""
    WhatsApp Food Ordering System

    A food ordering system with WhatsApp integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_order_orders_order_id_delete(self) -> None:
        """Test case for cancel_order_orders_order_id_delete

        Cancel Order
        """
        pass

    def test_create_menu_item_menu_post(self) -> None:
        """Test case for create_menu_item_menu_post

        Create Menu Item
        """
        pass

    def test_create_order_orders_post(self) -> None:
        """Test case for create_order_orders_post

        Create Order
        """
        pass

    def test_delete_menu_item_menu_item_id_delete(self) -> None:
        """Test case for delete_menu_item_menu_item_id_delete

        Delete Menu Item
        """
        pass

    def test_get_menu_item_menu_item_id_get(self) -> None:
        """Test case for get_menu_item_menu_item_id_get

        Get Menu Item
        """
        pass

    def test_get_menu_menu_get(self) -> None:
        """Test case for get_menu_menu_get

        Get Menu
        """
        pass

    def test_get_order_orders_order_id_get(self) -> None:
        """Test case for get_order_orders_order_id_get

        Get Order
        """
        pass

    def test_get_orders_orders_get(self) -> None:
        """Test case for get_orders_orders_get

        Get Orders
        """
        pass

    def test_update_menu_item_menu_item_id_patch(self) -> None:
        """Test case for update_menu_item_menu_item_id_patch

        Update Menu Item
        """
        pass

    def test_update_order_status_orders_order_id_patch(self) -> None:
        """Test case for update_order_status_orders_order_id_patch

        Update Order Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
