# coding: utf-8

"""
    WhatsApp Food Ordering System

    A food ordering system with WhatsApp integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.menu_item_create import MenuItemCreate

class TestMenuItemCreate(unittest.TestCase):
    """MenuItemCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MenuItemCreate:
        """Test MenuItemCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MenuItemCreate`
        """
        model = MenuItemCreate()
        if include_optional:
            return MenuItemCreate(
                name = '',
                description = '',
                price = 1.337,
                is_available = True
            )
        else:
            return MenuItemCreate(
                name = '',
                description = '',
                price = 1.337,
        )
        """

    def testMenuItemCreate(self):
        """Test MenuItemCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
