# coding: utf-8

"""
    WhatsApp Food Ordering System

    A food ordering system with WhatsApp integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_out import OrderOut

class TestOrderOut(unittest.TestCase):
    """OrderOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderOut:
        """Test OrderOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderOut`
        """
        model = OrderOut()
        if include_optional:
            return OrderOut(
                customer_name = '',
                whatsapp_number = '',
                id = 56,
                status = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cancelled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                items = [
                    openapi_client.models.order_item_out.OrderItemOut(
                        menu_item_id = 56, 
                        quantity = 56, 
                        id = 56, )
                    ]
            )
        else:
            return OrderOut(
                customer_name = '',
                whatsapp_number = '',
                id = 56,
                status = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                items = [
                    openapi_client.models.order_item_out.OrderItemOut(
                        menu_item_id = 56, 
                        quantity = 56, 
                        id = 56, )
                    ],
        )
        """

    def testOrderOut(self):
        """Test OrderOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
